### ISSUE TITLE
Update NewPipe Extractor to latest one

### ISSUE THREAD

**Issue by ShareASmile** [juanpaulconte/teste#3]
To fix following issues:
1) No comments being fetched on yt videos
2) Watching age restricted yt videos
3) yt Channel page continuations
4) SoundCloud issues & many more.

**Comment by ShareASmile** [comment]
Also We should change the fork to following repository which has the most fixes:
https://github.com/blackbox87/NewPipe-legacy

**Comment by juanpaulconte** [comment]
Sorry for the long delay.

Today released [v0.19.8.2](https://github.com/juanpaulconte/teste/releases/tag/v0.19.8.2) with NewPipeExtractor v0.21.8, that fixes extraction of YouTube's decryption function.

**Comment by juanpaulconte** [comment]
I've synchronized this repository with [juanpaulconte/NewPipe-legacy,](https://github.com/juanpaulconte/NewPipe-legacy) future updates will be made on that repository, because I've managed to lost the hierarchy/relation of this repository to the [TeamNewPipe/NewPipe-legacy](https://github.com/TeamNewPipe/NewPipe-legacy).
